name: Deploy master branch

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    environment:
      name: Prod
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run coverage
    - uses: codecov/codecov-action@v1
    - name: serverless deploy
      uses: serverless/github-action@master
      with:
        args: deploy --stage prod
      env:
        SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
        # or if using AWS credentials directly
        # AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        # AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    - name: Create Sentry release
      uses: getsentry/action-release@v1
      env:
        SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        SENTRY_ORG: messagine
        SENTRY_PROJECT: messagine-bot
      with:
        environment: production
    - name: call serverless endpoint url
      uses: wei/curl@v1.1.1
      with:
        args: ${{ secrets.SERVERLESS_ENDPOINT_URL }}
